consul:
  image: progrium/consul:latest
  command: -server -bootstrap -rejoin
  ports:
    - "8500:8500"

service:
  build: ./service
  environment:
    - MICRO_REGISTRY_ADDRESS=consul:8500
  links:
    - consul
  command: /go/bin/service

service-client:
  build: ./service-client
  environment:
      - MICRO_REGISTRY_ADDRESS=consul:8500
  links:
    - consul
  command: /go/bin/service-client
  ports:
    - "8080:8080"

sidecar:
  build: ./sidecar
  environment:
    - MICRO_REGISTRY_ADDRESS=consul:8500
  links:
    - consul
  command: micro --enable_stats sidecar
  ports:
    - "8081:8081"

