// Code generated by protoc-gen-go.
// source: proto.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto.proto

It has these top-level messages:
	PingRequest
	PingResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto1.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingResponse struct {
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto1.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*PingRequest)(nil), "PingRequest")
	proto1.RegisterType((*PingResponse)(nil), "PingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for HealthCheck service

type HealthCheckClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PingResponse, error)
}

type healthCheckClient struct {
	c           client.Client
	serviceName string
}

func NewHealthCheckClient(serviceName string, c client.Client) HealthCheckClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "healthcheck"
	}
	return &healthCheckClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *healthCheckClient) Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PingResponse, error) {
	req := c.c.NewRequest(c.serviceName, "HealthCheck.Ping", in)
	out := new(PingResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HealthCheck service

type HealthCheckHandler interface {
	Ping(context.Context, *PingRequest, *PingResponse) error
}

func RegisterHealthCheckHandler(s server.Server, hdlr HealthCheckHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&HealthCheck{hdlr}, opts...))
}

type HealthCheck struct {
	HealthCheckHandler
}

func (h *HealthCheck) Ping(ctx context.Context, in *PingRequest, out *PingResponse) error {
	return h.HealthCheckHandler.Ping(ctx, in, out)
}

func init() { proto1.RegisterFile("proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x03, 0x93, 0x4a, 0xbc, 0x5c, 0xdc, 0x01, 0x99, 0x79, 0xe9, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x4a, 0x1a, 0x5c, 0x3c, 0x10, 0x6e, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90,
	0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x8c, 0x6b, 0x64, 0xc2, 0xc5, 0xed, 0x91, 0x9a, 0x98, 0x53, 0x92, 0xe1, 0x9c, 0x91, 0x9a,
	0x9c, 0x2d, 0xa4, 0xca, 0xc5, 0x02, 0xd2, 0x28, 0xc4, 0xa3, 0x87, 0x64, 0x9c, 0x14, 0xaf, 0x1e,
	0xb2, 0x69, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x5b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xff,
	0x6d, 0xf3, 0x72, 0x84, 0x00, 0x00, 0x00,
}
